### PR TITLE
Add `RetryUntil` to timed package

### PR DESCRIPTION
**Pull request by kvch**
The new function `RetryUntil` executes a function periodically until it succeeds or the timeout is elapsed. It can be used when you have to wait until some condition becomes true, or something no longer returns an error.

### CODE REVIEW

**Comment by kvch** [comment]
I've signed the CLA.

**Review by urso — COMMENTED** [review]
LGTM.

This change also enables a pattern like this:

```
tg := TaskGroupWithCancel(ctx)

// this stop handler would also be nice to have in go-concert
tg.OnStop = func(err error) (unison.TaskGroupStopAction, error) {
  if err == nil || err == context.Cancelled { // stop all workers on success or if the context got cancelled
    return unison.TaskGroupStopActionShutdown, nil
  }

  // continue other tasks if we've seen one client fail or timeout
  return unison.TaskGroupStopActionContinue, err  
}

for _, client := range clients {
  tg.Go(func(ctx context.Context) error {
    return timed.RetryUntil(ctx, 1 * time.Minute, 200 * time.Millisecond, func(ctx context.Context) error {
      return client.Send(ctx, ...)
    })
  })
 
  // wait max 250ms for the send operation to succeed, otherwise we attempt a concurrent a send on the next client
  if err := timed.Wait(tg.Context(), 250 * time.Millisecond); err != nil {
    // the taskgroup was cancelled because one client did succeed or the parent context got cancelled , stop immediately
    break
  }
}

return tg.Stop()
```

**Comment by kvch** [comment]
@cmacknz Could you please take a look at this PR? We use this lib, and thought we could contribute some code back. :)

**Comment by cmacknz** [comment]
It seems I don't have permissions to do anything on this repository. @v1v are you able to add me as an admin for this repository?

**Review by cmacknz — APPROVED** [review]

**Pull request merged**
